language: python
python:
  - "pypy"
  - 2.6
  - 2.7
  - "2.7_with_system_site_packages"
  - 3.2
  - "3.2_with_system_site_packages"
  - 3.3
install:
  - pip install -r requirements.txt
script:
  - pytest 
notifications:
  email: false
